on:
  push:
    branches:
      - master

name: deploy

jobs:
  deploy:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUBPAT }}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@master

      - name: Deploy examples
        run: |
          chmod +x ./deploy.sh
          ./deploy.sh
